version: "2.2"

networks:
  default:
  proxy:
    external:
      name: nginx-proxy

services:
  mysql:
    extends:
      file: ../../../common.yml
      service: mysql
    container_name: ${PROJECT}-mysql
    volumes:
      - "${BASEDIR}/var/lib/mysql:/var/lib/mysql"
      - "${BASEDIR}/var/log/mysql:/var/log/mysql"
      - "${BASEDIR}/var/tmp/mysql:/var/tmp/mysql"
    environment:
      - TERM=${TERM}
      - ENVIRONMENT=${ENVIRONMENT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_DB}
      - MYSQL_PASS=${MYSQL_DB}
    networks:
      - default

  drupal:
    image: unocha/${PROJECT}-site:${TAG:-local}
    container_name: ${PROJECT}-drupal
    scale: 1
    volumes:
      - "${BASEDIR}/srv/www:/srv/www:rw"
      - "${BASEDIR}/srv/www/html:/srv/www/html:rw"
      - "${BASEDIR}/srv/www/docker/settings.php:/srv/www/html/sites/default/settings.php:rw"
      - "${BASEDIR}/srv/www/docker/services.yml:/srv/www/html/sites/default/services.yml:rw"
      - "${BASEDIR}/var/log/nginx:/var/log/nginx:rw"
      - "${BASEDIR}/var/log/php:/var/log/php:rw"
      - "${BASEDIR}/srv/database:/srv/www/database:rw"
      - "${BASEDIR}/srv/shared:/srv/www/shared:rw"
      - "${BASEDIR}/srv/shared/files:/srv/www/html/sites/default/files:rw"
      - "${BASEDIR}/srv/shared/private:/srv/www/html/sites/default/private:rw"
      - "${BASEDIR}/tmp:/tmp:rw"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PHP_ENVIRONMENT=${PHP_ENVIRONMENT}
      - TERM=${TERM}
      - NGINX_SERVERNAME=${NGINX_SERVERNAME}
      - NGINX_OVERRIDE_PROTOCOL=${NGINX_SERVERNAME}
      - LETSENCRYPT_EMAIL=ops+${PROJECT}@humanitarianresponse.info
      - LETSENCRYPT_HOST=${NGINX_SERVERNAME}
      - VIRTUAL_HOST=${NGINX_SERVERNAME}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=nginx-proxy
      - DRUSH_OPTIONS_URI=https://${NGINX_SERVERNAME}
      - HTTPS_METHOD=noredirect
      - DRUPAL_DB_DATABASE=${MYSQL_DB}
      - DRUPAL_DB_USERNAME=${MYSQL_DB}
      - DRUPAL_DB_PASSWORD=${MYSQL_DB}
      - DRUPAL_DB_HOST=mysql
      - DRUPAL_DB_DRIVER=mysql
    depends_on:
      - mysql
    networks:
      - default
      - proxy
