version: "2.2"

networks:
  default:
  proxy:
    external:
      name: nginx-proxy

services:
  mysql:
    extends:
      file: ../../../common.yml
      service: mysql
    container_name: ${PROJECT}-mysql
    volumes:
      - "${BASEDIR}/var/lib/mysql:/var/lib/mysql"
      - "${BASEDIR}/var/log/mysql:/var/log/mysql"
      - "${BASEDIR}/var/tmp/mysql:/var/tmp/mysql"
    environment:
      - TERM=${TERM:-xterm}
      - ENVIRONMENT=${ENVIRONMENT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_DB}
      - MYSQL_PASS=${MYSQL_DB}
    networks:
      default:
        aliases:
          # This is to avoid clashes in case there is another `mysql` on one of
          # the networks the `drupal` service is connected to, and allow to
          # connect another DB for example for Drupal 7 to Drupal 8 migration.
          - mysql.${PREFIX}

  drupal:
    image: unocha/${PROJECT}:${TAG:-local}
    container_name: ${PROJECT}-drupal
    scale: 1
    volumes:
      - "${SITEREPODIR}:/srv/www:rw"
      - "${SITEREPODIR}/docker/settings.php:/srv/www/html/sites/default/settings.php:rw"
      - "${SITEREPODIR}/docker/services.yml:/srv/www/html/sites/default/services.yml:rw"
      - "${BASEDIR}/var/log/nginx:/var/log/nginx:rw"
      - "${BASEDIR}/var/log/php:/var/log/php:rw"
      - "${BASEDIR}/srv/www/database:/srv/www/database:rw"
      - "${BASEDIR}/srv/www/shared:/srv/www/shared:rw"
      - "${BASEDIR}/srv/www/shared/files:/srv/www/html/sites/default/files:rw"
      - "${BASEDIR}/srv/www/shared/private:/srv/www/html/sites/default/private:rw"
      - "${BASEDIR}/tmp:/tmp:rw"
      - /dev/log:/dev/log
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PHP_ENVIRONMENT=${PHP_ENVIRONMENT}
      - TERM=${TERM:-xterm}
      - NGINX_SERVERNAME=${NGINX_SERVERNAME}
      - NGINX_OVERRIDE_PROTOCOL=${NGINX_SERVERNAME}
      - LETSENCRYPT_EMAIL=ops+${PREFIX}@humanitarianresponse.info
      - LETSENCRYPT_HOST=${NGINX_SERVERNAME}
      - VIRTUAL_HOST=${NGINX_SERVERNAME}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=nginx-proxy
      - DRUSH_OPTIONS_URI=https://${NGINX_SERVERNAME}
      - HTTPS_METHOD=noredirect
      - DRUPAL_DB_DATABASE=${MYSQL_DB}
      - DRUPAL_DB_USERNAME=${MYSQL_DB}
      - DRUPAL_DB_PASSWORD=${MYSQL_DB}
      - DRUPAL_DB_HOST=mysql.${PREFIX}
      - DRUPAL_DB_DRIVER=mysql
      - PHP_XDEBUG=${PHP_XDEBUG}
      - PHP_XDEBUG_DEFAULT_ENABLE=${PHP_XDEBUG_DEFAULT_ENABLE}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK}
      - PHP_XDEBUG_REMOTE_ENABLE=${PHP_XDEBUG_REMOTE_ENABLE}
      - PHP_XDEBUG_LOG=${PHP_XDEBUG_LOG}
      - PHP_OPCACHE_ENABLE=${PHP_OPCACHE_ENABLE}
      - SOLR_CORE=${SOLR_CORE:-solr}
    networks:
      - default
      - proxy
    depends_on:
      - mysql

  # *Only if the stack requires solr.*
  # (the first line is a follow-on from the drupal depends_on list.)
      - solr

  solr:
    extends:
      file: ../../../common.yml
      service: solr
    container_name: ${PROJECT}-solr
    volumes:
      - "${BASEDIR}/tmp:/tmp:rw"
      - "${BASEDIR}/srv/solr:/var/solr"
      - "${BASEDIR}/srv/backups:/srv/backups"
      - "./etc/solr/configsets:/configsets"
    environment:
      - TERM=xterm
      - SOLR_CORE=${SOLR_CORE:-solr}
    command:
      - solr-precreate
      - ${SOLR_CORE:-solr}
      - /configsets/${SOLR_SCHEMA:-drupal}
    networks:
      default:
        aliases:
          # This is to avoid clashes in case there is another `solr` on one of
          # the networks the `drupal` service is connected to.
          - solr.${PREFIX}
