version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: local-reverse-proxy
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./etc/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
