version: "2.2"

services:
  proxy:
    image: public.ecr.aws/unocha/caddy:2.6.2
    container_name: local-reverse-proxy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
    - ./etc/caddy:/etc/caddy
    - ./var/config:/config
    - ./var/data:/data
    - ./var/logs:/logs
    - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /etc/caddy
    environment:
      CADDY_DOCKER_CADDYFILE_PATH: /etc/caddy/Caddyfile
      CADDY_INGRESS_NETWORKS: proxy
      CADDY_DOCKER_POLLING_INTERVAL: 5s
    restart: unless-stopped
    networks:
      proxy:

networks:
  proxy:
    external: true
