version: "2.2"

networks:
  default:
  proxy:
    external:
      name: proxy

services:
  mysql:
    image: public.ecr.aws/unocha/mysql:10.6
    container_name: ${PROJECT}-mysql
    volumes:
      - "${BASEDIR}/var/lib/mysql:/var/lib/mysql"
      - "${BASEDIR}/var/log/mysql:/var/log/mysql"
      - "${BASEDIR}/var/tmp/mysql:/var/tmp/mysql"
    environment:
      - TERM=${TERM:-xterm}
      - ENVIRONMENT=${ENVIRONMENT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_DB}
      - MYSQL_PASS=${MYSQL_DB}
    networks:
      default:
        aliases:
          # This is to avoid clashes in case there is another `mysql` on one of
          # the networks the `drupal` service is connected to, and allow to
          # connect another DB for example for Drupal 7 to Drupal 8 migration.
          - mysql.${PREFIX}

  drupal:
    image: public.ecr.aws/unocha/${PROJECT}-site:${TAG:-local}
    container_name: ${PROJECT}-drupal
    scale: 1
    volumes:
      - "${SITEREPODIR}:/srv/www:rw"
      - "${BASEDIR}/var/log/nginx:/var/log/nginx:rw"
      - "${BASEDIR}/var/log/php:/var/log/php:rw"
      - "${BASEDIR}/srv/www/database:/srv/www/database:rw"
      - "${BASEDIR}/srv/www/shared:/srv/www/shared:rw"
      - "${BASEDIR}/srv/www/shared/files:/srv/www/html/sites/default/files:rw"
      - "${BASEDIR}/srv/www/shared/private:/srv/www/html/sites/default/private:rw"
      - "${BASEDIR}/tmp:/tmp:rw"
      - /dev/log:/dev/log
    environment:
      ENVIRONMENT:
      PHP_ENVIRONMENT:
      TERM=${TERM:-xterm}
      NGINX_SERVERNAME:
      NGINX_OVERRIDE_PROTOCOL:
      NGINX_LIMIT_HUMANS:
      NGINX_BURST_HUMANS:
      DRUSH_OPTIONS_URI=https://${NGINX_SERVERNAME}
      DRUPAL_DB_DATABASE=${MYSQL_DB}
      DRUPAL_DB_USERNAME=${MYSQL_DB}
      DRUPAL_DB_PASSWORD=${MYSQL_DB}
      DRUPAL_DB_HOST=mysql.${PREFIX}
      DRUPAL_DB_DRIVER=mysql
      PHP_XDEBUG:
      PHP_XDEBUG_DEFAULT_ENABLE:
      PHP_XDEBUG_REMOTE_AUTOSTART:
      PHP_XDEBUG_REMOTE_CONNECT_BACK:
      PHP_XDEBUG_REMOTE_ENABLE:
      PHP_XDEBUG_LOG:
      PHP_OPCACHE_ENABLE:
      PHP_MEMORY_LIMIT:
      SOLR_CORE=${SOLR_CORE:-solr}
    labels:
      caddy: ${NGINX_SERVERNAME}
      caddy.reverse_proxy: "{{upstreams}}"
    networks:
      - default
      - proxy
    depends_on:
      - mysql

  # *Only if the stack requires solr.*
  # (the first line is a follow-on from the drupal depends_on list.)
      - solr

  solr:
    image: solr:8.11.2-slim
    hostname: ${PROJECT}-${STACK}-solr
    container_name: ${PROJECT}-solr
    volumes:
      - "${BASEDIR}/tmp:/tmp:rw"
      - "${BASEDIR}/srv/solr:/var/solr"
      - "${BASEDIR}/srv/backups:/srv/backups"
      - "./etc/solr/configsets:/configsets"
    environment:
      - TERM=xterm
      - SOLR_CORE=${SOLR_CORE:-solr}
    command:
      - solr-precreate
      - ${SOLR_CORE:-solr}
      - /configsets/${SOLR_SCHEMA:-drupal}
    networks:
      default:
        aliases:
          # This is to avoid clashes in case there is another `solr` on one of
          # the networks the `drupal` service is connected to.
          - solr.${PREFIX}
